# Generated by Django 5.0.3 on 2024-03-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_warehouses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouses',
            name='price',
            field=models.IntegerField(),
        ),
    ]
